# Generated by Django 4.2.14 on 2024-08-05 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='oponnent',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player',
        ),
    ]
