# Generated by Django 4.2.14 on 2024-08-05 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_game_oponnent_remove_game_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.player'),
        ),
    ]
