# Generated by Django 4.2.14 on 2024-08-06 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_opponent_alter_game_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
